// ============================================================
// أماكنُ المغرب — الجماعاتُ والمراكزُ الصغيرة.
//
//   وُلد هذا الملفّ من قياسٍ ميدانيّ: عند مزامنة مدن Livo ظهر أنّ المحرّكَ
//   يفهم **٣٤ من ٤٤١** — و٤٠٧ أماكنَ تُرسَل أسماؤها نصًّا خامًّا بلا تطبيع
//   ولا اقتراحٍ للتاجر.
//
//   والقرارُ المعماريُّ الأهمُّ هنا: **هذه ليست «مدنَ Livo».** هي أماكنُ
//   المغرب. لو بدّل المالكُ شركةَ التوصيل غدًا لبقيت المعرفةُ عنده — ولو
//   ربطناها بالشركة لضاعت معها. الشركةُ تُعطي مُعرِّفاتِها، والمكانُ عندنا.
//
//   ولذلك لا حقلَ `id` هنا: مُعرِّفُ الشركة يعيش في جدول الربط
//   (`external_city_id`)، لا في المعرفة نفسِها.
//
//   `CITIES` في `knowledgeData` تبقى للمدن الكبرى بأحيائها؛ هذه تُكمّلها
//   بالأماكن الصغيرة. الدمجُ في `places.ts` — مصدرٌ واحدٌ للقراءة.
// ============================================================

export interface PlaceData {
  ar: string;
  fr: string;
  /** أشكالٌ مُطبَّعةٌ للمطابقة — عربيّةٌ ولاتينيّة. */
  aliases: string[];
}

export const PLACES: PlaceData[] = [
  { ar: 'طانطان', fr: 'Tantan', aliases: ['tantan'] },
  { ar: 'سيدي عبد الله غيات', fr: 'Sidi Abdellah Ghiat', aliases: ['sidi abdellah ghiat'] },
  { ar: 'تيفلت', fr: 'Tiflet', aliases: ['tiflet'] },
  { ar: 'الصخيرات', fr: 'Skhirat', aliases: ['skhirat'] },
  { ar: 'سايس', fr: 'Saiss', aliases: ['saiss'] },
  { ar: 'أغمات', fr: 'Aghmat', aliases: ['aghmat'] },
  { ar: 'بني واسين', fr: 'Beni Ouassine', aliases: ['beni ouassine'] },
  { ar: 'بلايا', fr: 'Playa', aliases: ['playa'] },
  { ar: 'أولاد سعيد', fr: 'Oulad Said', aliases: ['oulad said'] },
  { ar: 'تاسيلتانت', fr: 'Taseltant', aliases: ['taseltant'] },
  { ar: 'بن جرير', fr: 'Ben Guerir', aliases: ['ben guerir'] },
  { ar: 'المنصورية', fr: 'El Mansouria', aliases: ['el mansouria'] },
  { ar: 'أولاد فرج', fr: 'Oulad Fraj', aliases: ['oulad fraj'] },
  { ar: 'سوق الأربعاء الغرب', fr: 'Souk Elarbaa Du Gharb', aliases: ['souk elarbaa du gharb'] },
  { ar: 'فجيج', fr: 'Figuig', aliases: ['figuig'] },
  { ar: 'مديونة', fr: 'Mediouna', aliases: ['mediouna'] },
  { ar: 'البزازة', fr: 'El Bazaza', aliases: ['el bazaza'] },
  { ar: 'أولاد إسماعيل', fr: 'Oulad Ismail', aliases: ['oulad ismail'] },
  { ar: 'قصبة تادلة', fr: 'Kasba Tadla', aliases: ['kasba tadla'] },
  { ar: 'تيولي', fr: 'Tiouli', aliases: ['tiouli'] },
  { ar: 'تيزي وسلي', fr: 'Tizi Ouasli', aliases: ['tizi ouasli'] },
  { ar: 'تويسيت', fr: 'Touissite', aliases: ['touissite'] },
  { ar: 'لعتامنة', fr: 'Laatamna', aliases: ['laatamna'] },
  { ar: 'أمزميز', fr: 'Amizmiz', aliases: ['amizmiz'] },
  { ar: 'أغورد', fr: 'Aghroud', aliases: ['aghroud'] },
  { ar: 'تارودانت', fr: 'Taroudant', aliases: ['taroudant'] },
  { ar: 'كلميم', fr: 'Guelmim', aliases: ['guelmim'] },
  { ar: 'مرتيل', fr: 'Martil', aliases: ['martil'] },
  { ar: 'بوفكران', fr: 'Boufakrane', aliases: ['boufakrane'] },
  { ar: 'سيدي إفني', fr: 'Sidi Ifni', aliases: ['sidi ifni'] },
  { ar: 'الريش', fr: 'Rich', aliases: ['rich'] },
  { ar: 'تالوين', fr: 'Taliouine', aliases: ['taliouine'] },
  { ar: 'دار الكبداني', fr: 'Dar El Kebdani', aliases: ['dar el kebdani'] },
  { ar: 'آيت باها', fr: 'Ait Baha', aliases: ['ait baha'] },
  { ar: 'فرخانة', fr: 'Farkhana', aliases: ['farkhana'] },
  { ar: 'لالة تاكركوست', fr: 'Lalla Takerkoust', aliases: ['lalla takerkoust'] },
  { ar: 'العين', fr: 'El Ain', aliases: ['el ain'] },
  { ar: 'زاوية الشيخ', fr: 'Zaouiat Cheikh', aliases: ['zaouiat cheikh'] },
  { ar: 'بوزنيقة', fr: 'Bouznika', aliases: ['bouznika'] },
  { ar: 'تمسية', fr: 'Temsia', aliases: ['temsia'] },
  { ar: 'فاديسا', fr: 'Fadesa', aliases: ['fadesa'] },
  { ar: 'إفران', fr: 'Ifrane', aliases: ['ifrane'] },
  { ar: 'أزرو', fr: 'Azrou', aliases: ['azrou'] },
  { ar: 'بيوكرى', fr: 'Biougra', aliases: ['biougra'] },
  { ar: 'تيط مليل', fr: 'Tit Mellil', aliases: ['tit mellil'] },
  { ar: 'بودربالة', fr: 'Bouderbala', aliases: ['bouderbala'] },
  { ar: 'بودنيب', fr: 'Boudnib', aliases: ['boudnib'] },
  { ar: 'بنسراݣو', fr: 'Benseragou', aliases: ['benseragou'] },
  { ar: 'جمعة سحيم', fr: 'Jamaat Shaim', aliases: ['jamaat shaim'] },
  { ar: 'الجرف', fr: 'Jerf', aliases: ['jerf'] },
  { ar: 'مارينا سمير', fr: 'Marina Smir', aliases: ['marina smir'] },
  { ar: 'آيت بن حدو', fr: 'Ait Ben Hadou', aliases: ['ait ben hadou'] },
  { ar: 'باب برد', fr: 'Bab Berred', aliases: ['bab berred'] },
  { ar: 'جهة مراكش', fr: 'Region Kech', aliases: ['region kech'] },
  { ar: 'ورزازات-تازناخت', fr: 'Ourzazate-Taznakht', aliases: ['ourzazate taznakht'] },
  { ar: 'تامسنا', fr: 'Tamesna', aliases: ['tamesna'] },
  { ar: 'العيايطة', fr: 'Laayayta', aliases: ['laayayta'] },
  { ar: 'ميضار', fr: 'Midar', aliases: ['midar'] },
  { ar: 'زمامرة', fr: 'Zemamra', aliases: ['zemamra'] },
  { ar: 'القصر الصغير', fr: 'Ksar Sghir', aliases: ['ksar sghir'] },
  { ar: 'تيداس', fr: 'Tiddas', aliases: ['tiddas'] },
  { ar: 'تغازوت', fr: 'Taghazout', aliases: ['taghazout'] },
  { ar: 'برشيد', fr: 'Berrchid', aliases: ['berrchid'] },
  { ar: 'مولاي إبراهيم', fr: 'Moulay Brahim', aliases: ['moulay brahim'] },
  { ar: 'نعيمة', fr: 'Naima', aliases: ['naima'] },
  { ar: 'القصيبة', fr: 'El Ksiba', aliases: ['el ksiba'] },
  { ar: 'بوزغلال', fr: 'Bouzaghlal', aliases: ['bouzaghlal'] },
  { ar: 'سوق الحد البرادية', fr: 'Souk El Had Des Bradia', aliases: ['souk el had des bradia'] },
  { ar: 'حد درعة', fr: 'Had Draa', aliases: ['had draa'] },
  { ar: 'مسمودة', fr: 'Msmouda', aliases: ['msmouda'] },
  { ar: 'بئر الجديد', fr: 'Bir Jdid', aliases: ['bir jdid'] },
  { ar: 'الفنيدق', fr: 'Fnideq', aliases: ['fnideq'] },
  { ar: 'أجدير - الحسيمة', fr: 'Ajdir - Al Hoceima', aliases: ['ajdir al hoceima'] },
  { ar: 'إمزورن', fr: 'Imzouren', aliases: ['imzouren'] },
  { ar: 'القصابي', fr: 'El Ksabi', aliases: ['el ksabi'] },
  { ar: 'أكرمود', fr: 'Akermoud', aliases: ['akermoud'] },
  { ar: 'أمليل', fr: 'Amlil', aliases: ['amlil'] },
  { ar: 'صفرو', fr: 'Sefrou', aliases: ['sefrou'] },
  { ar: 'جعادر', fr: 'Jaadar', aliases: ['jaadar'] },
  { ar: 'الحاج قدور', fr: 'El Haj Kaddour', aliases: ['el haj kaddour'] },
  { ar: 'بولنوار', fr: 'Boulenouar', aliases: ['boulenouar'] },
  { ar: 'بوعنان', fr: 'Bouanane', aliases: ['bouanane'] },
  { ar: 'زايدة', fr: 'Zaida', aliases: ['zaida'] },
  { ar: 'عين بيضة', fr: 'Ain Beda', aliases: ['ain beda'] },
  { ar: 'اليوسفية', fr: 'Youssoufia', aliases: ['youssoufia'] },
  { ar: 'زايو زغنغان', fr: 'Zeghanghane', aliases: ['zeghanghane'] },
  { ar: 'سيدي بوزيد', fr: 'Sidi Bouzid', aliases: ['sidi bouzid'] },
  { ar: 'تازة', fr: 'Tazaa', aliases: ['tazaa'] },
  { ar: 'بوجعد', fr: 'Boujad', aliases: ['boujad'] },
  { ar: 'سبت اݣزولة', fr: 'Sebt Gzoula', aliases: ['sebt gzoula'] },
  { ar: 'الوداية', fr: 'Loudaya', aliases: ['loudaya'] },
  { ar: 'آيت ملك', fr: 'Ait Milk', aliases: ['ait milk'] },
  { ar: 'سبع عيون', fr: 'Sebaa Ayoune', aliases: ['sebaa ayoune'] },
  { ar: 'المريس', fr: 'Lamriss', aliases: ['lamriss'] },
  { ar: 'أسام', fr: 'Assam', aliases: ['assam'] },
  { ar: 'سبت الݣردان', fr: 'Sebt Lguerdan', aliases: ['sebt lguerdan'] },
  { ar: 'باب مرزوقة', fr: 'Bab Marzouka', aliases: ['bab marzouka'] },
  { ar: 'بوسكورة', fr: 'Bouskoura', aliases: ['bouskoura'] },
  { ar: 'سيدي حرازم', fr: 'Sidi Harazem', aliases: ['sidi harazem'] },
  { ar: 'تاونات', fr: 'Taounat', aliases: ['taounat'] },
  { ar: 'نوينويش', fr: 'Nouinouiche', aliases: ['nouinouiche'] },
  { ar: 'لالة ميمونة', fr: 'Lala Mimouna', aliases: ['lala mimouna'] },
  { ar: 'أولاد برجال', fr: 'Ouled Berjal', aliases: ['ouled berjal'] },
  { ar: 'ݣيسر', fr: 'Guisser', aliases: ['guisser'] },
  { ar: 'تيكوين', fr: 'Tikiouine', aliases: ['tikiouine'] },
  { ar: 'ݣرسيف', fr: 'Guercif', aliases: ['guercif'] },
  { ar: 'سيدي علال البحراوي', fr: 'Sidi Allal El Bahraoui', aliases: ['sidi allal el bahraoui'] },
  { ar: 'ݣنفودة', fr: 'Guenfouda', aliases: ['guenfouda'] },
  { ar: 'السويهلة', fr: 'Souihla', aliases: ['souihla'] },
  { ar: 'قلعة مݣونة', fr: 'Kelaat M\'Gouna', aliases: ['kelaat m gouna'] },
  { ar: 'ولماس', fr: 'Oulmes', aliases: ['oulmes'] },
  { ar: 'تاوريرت', fr: 'Taourirt', aliases: ['taourirt'] },
  { ar: 'إهضاضن', fr: 'Ihadaden', aliases: ['ihadaden'] },
  { ar: 'الشويطر', fr: 'Elshwitar', aliases: ['elshwitar'] },
  { ar: 'آيت يوسف', fr: 'Ait Youssef', aliases: ['ait youssef'] },
  { ar: 'شلالات', fr: 'Chellalat', aliases: ['chellalat'] },
  { ar: 'بريكشة', fr: 'Briksha', aliases: ['briksha'] },
  { ar: 'الفقيه بن صالح', fr: 'Fkih Ben Salah', aliases: ['fkih ben salah'] },
  { ar: 'تازة', fr: 'Taza', aliases: ['taza'] },
  { ar: 'أكنول', fr: 'Aknoul', aliases: ['aknoul'] },
  { ar: 'خميس زمامرة', fr: 'Khmis Zmamra', aliases: ['khmis zmamra'] },
  { ar: 'الوالدية', fr: 'Oualidia', aliases: ['oualidia'] },
  { ar: 'مولاي بوسلهام', fr: 'Moulay Bousselham', aliases: ['moulay bousselham'] },
  { ar: 'خريبكة', fr: 'Khouribga', aliases: ['khouribga'] },
  { ar: 'عين الله', fr: 'Ain Allah', aliases: ['ain allah'] },
  { ar: 'الدروة', fr: 'Deroua', aliases: ['deroua'] },
  { ar: 'الحوزية', fr: 'Haouzia', aliases: ['haouzia'] },
  { ar: 'الرحمة', fr: 'Errahma', aliases: ['errahma'] },
  { ar: 'جرادة', fr: 'Jerada', aliases: ['jerada'] },
  { ar: 'الريصاني', fr: 'Risani', aliases: ['risani'] },
  { ar: 'آيت ملول', fr: 'Ait Melloul', aliases: ['ait melloul'] },
  { ar: 'بركان', fr: 'Berkane', aliases: ['berkane'] },
  { ar: 'قرية أركمان', fr: 'Kariat Arekmane', aliases: ['kariat arekmane'] },
  { ar: 'كتارة', fr: 'Kettara', aliases: ['kettara'] },
  { ar: 'آيت أومربط', fr: 'Ait Oumribet', aliases: ['ait oumribet'] },
  { ar: 'مشرع بلقصيري', fr: 'Mechraa Belksiri', aliases: ['mechraa belksiri'] },
  { ar: 'وزان', fr: 'Ouazzane', aliases: ['ouazzane'] },
  { ar: 'الرميلات', fr: 'Rmilat', aliases: ['rmilat'] },
  { ar: 'مرس الخير', fr: 'Mers El Lkhir', aliases: ['mers el lkhir'] },
  { ar: 'هوارة', fr: 'Houara', aliases: ['houara'] },
  { ar: 'أولاد غانم', fr: 'Oulad Ghanem', aliases: ['oulad ghanem'] },
  { ar: 'إمنتانوت', fr: 'Imintanoute', aliases: ['imintanoute'] },
  { ar: 'سيدي بوقنادل', fr: 'Sidi Bouknadel', aliases: ['sidi bouknadel'] },
  { ar: 'بومالن دادس', fr: 'Boumalne Dades', aliases: ['boumalne dades'] },
  { ar: 'أشقار', fr: 'Achakar', aliases: ['achakar'] },
  { ar: 'زوالث دخيسة', fr: 'Zoualeth Dkhissa', aliases: ['zoualeth dkhissa'] },
  { ar: 'المنابهة', fr: 'Lamnabeha', aliases: ['lamnabeha'] },
  { ar: 'أحفير', fr: 'Ahfir', aliases: ['ahfir'] },
  { ar: 'أصيلة', fr: 'Asilah', aliases: ['asilah'] },
  { ar: 'بساتين المنزه', fr: 'Basatine El Manzeh', aliases: ['basatine el manzeh'] },
  { ar: 'أرفود', fr: 'Arfoud', aliases: ['arfoud'] },
  { ar: 'فرياطة', fr: 'Faryata', aliases: ['faryata'] },
  { ar: 'رأس الماء', fr: 'Ras El Ma', aliases: ['ras el ma'] },
  { ar: 'الدشيرة الجهادية', fr: 'Dcheira El Jihadia', aliases: ['dcheira el jihadia'] },
  { ar: 'بنسليمان', fr: 'Benslimane', aliases: ['benslimane'] },
  { ar: 'مولاي إدريس زرهون', fr: 'Moulay Idriss Zerhoun', aliases: ['moulay idriss zerhoun'] },
  { ar: 'الرشيدية', fr: 'Errachidia', aliases: ['errachidia'] },
  { ar: 'بني بوعياش - الحسيمة', fr: 'Bni Bouayach - Al Hoceima', aliases: ['bni bouayach al hoceima'] },
  { ar: 'معزيز', fr: 'Maaziz', aliases: ['maaziz'] },
  { ar: 'الشويطر', fr: 'Chouiter', aliases: ['chouiter'] },
  { ar: 'تفرسيت', fr: 'Tafersit', aliases: ['tafersit'] },
  { ar: 'ميرلفت', fr: 'Mirleft', aliases: ['mirleft'] },
  { ar: 'لحري', fr: 'Lahri', aliases: ['lahri'] },
  { ar: 'آيت عيسى', fr: 'Ait Aizza', aliases: ['ait aizza'] },
  { ar: 'سبع عيون', fr: 'Sabaa Aiyoun', aliases: ['sabaa aiyoun'] },
  { ar: 'أولاد دحو', fr: 'Oulad Dahhou', aliases: ['oulad dahhou'] },
  { ar: 'خنيفرة', fr: 'Khenifra', aliases: ['khenifra'] },
  { ar: 'زايو', fr: 'Zaio', aliases: ['zaio'] },
  { ar: 'بولمان', fr: 'Boulemane', aliases: ['boulemane'] },
  { ar: 'الفوارات', fr: 'Fouarat', aliases: ['fouarat'] },
  { ar: 'تالمست', fr: 'Talmest', aliases: ['talmest'] },
  { ar: 'بلاعݣيد', fr: 'Belaaguid', aliases: ['belaaguid'] },
  { ar: 'سيدي سماعيل', fr: 'Sidi Smail', aliases: ['sidi smail'] },
  { ar: 'سيدي يحيى الغرب', fr: 'Sidi Yahya Gharb', aliases: ['sidi yahya gharb'] },
  { ar: 'سميمو', fr: 'Smimou', aliases: ['smimou'] },
  { ar: 'دار بوعزة', fr: 'Dar Bouazza', aliases: ['dar bouazza'] },
  { ar: 'العرائش', fr: 'Larache', aliases: ['larache'] },
  { ar: 'بن أحمد', fr: 'Ben Ahmed', aliases: ['ben ahmed'] },
  { ar: 'فم وادي', fr: 'Foum Oudi', aliases: ['foum oudi'] },
  { ar: 'أزيلال', fr: 'Azilal', aliases: ['azilal'] },
  { ar: 'الشرفية', fr: 'Cherifia', aliases: ['cherifia'] },
  { ar: 'تدارت - تازة', fr: 'Taddart - Taza', aliases: ['taddart taza'] },
  { ar: 'أمسا', fr: 'Amsa', aliases: ['amsa'] },
  { ar: 'سيدي قاسم', fr: 'Sidi Kacem', aliases: ['sidi kacem'] },
  { ar: 'سيدي إسحاق', fr: 'Sidi Ishaq', aliases: ['sidi ishaq'] },
  { ar: 'إساكن', fr: 'Issaguen', aliases: ['issaguen'] },
  { ar: 'بنرحمون', fr: 'Benrahmoune', aliases: ['benrahmoune'] },
  { ar: 'تاغارت', fr: 'Tagharte', aliases: ['tagharte'] },
  { ar: 'واد أمليل', fr: 'Oued Amlil', aliases: ['oued amlil'] },
  { ar: 'قادار', fr: 'Kadar', aliases: ['kadar'] },
  { ar: 'كابو نيݣرو', fr: 'Cabo Negro', aliases: ['cabo negro'] },
  { ar: 'سيدي الطيبي', fr: 'Sidi Taibi', aliases: ['sidi taibi'] },
  { ar: 'مداغ', fr: 'Madagh', aliases: ['madagh'] },
  { ar: 'ورزازات', fr: 'Ouarzazate', aliases: ['ouarzazate'] },
  { ar: 'أولاد تايمة', fr: 'Oulad Teima', aliases: ['oulad teima'] },
  { ar: 'خنيشات', fr: 'Khenichet', aliases: ['khenichet'] },
  { ar: 'الخميسات', fr: 'Khemissat', aliases: ['khemissat'] },
  { ar: 'إنزكان', fr: 'Inezgane', aliases: ['inezgane'] },
  { ar: 'دمنات', fr: 'Demnate', aliases: ['demnate'] },
  { ar: 'ميسور', fr: 'Missour', aliases: ['missour'] },
  { ar: 'تندرارة', fr: 'Tenrara', aliases: ['tenrara'] },
  { ar: 'مسكالة', fr: 'Meskala', aliases: ['meskala'] },
  { ar: 'عين بني مطهر', fr: 'Ain Beni Mathar', aliases: ['ain beni mathar'] },
  { ar: 'سكورة', fr: 'Skoura', aliases: ['skoura'] },
  { ar: 'حطان', fr: 'Hattane', aliases: ['hattane'] },
  { ar: 'سيدي عايدي', fr: 'Sidi Aidi', aliases: ['sidi aidi'] },
  { ar: 'أولاد موسى', fr: 'Oulad Moussa', aliases: ['oulad moussa'] },
  { ar: 'إيموزار', fr: 'Imouzzer', aliases: ['imouzzer'] },
  { ar: 'آيت أميرة', fr: 'Ait Amira', aliases: ['ait amira'] },
  { ar: 'المنار', fr: 'Mnar', aliases: ['mnar'] },
  { ar: 'اثنين غيات', fr: 'Tnin Ghiat', aliases: ['tnin ghiat'] },
  { ar: 'أولاد زمام', fr: 'Oulad Zmam', aliases: ['oulad zmam'] },
  { ar: 'مشرع بلقصيري', fr: 'Mechra Bel Ksiri', aliases: ['mechra bel ksiri'] },
  { ar: 'دوار سيدي علي', fr: 'Douar Sidi Ali', aliases: ['douar sidi ali'] },
  { ar: 'عين الركادة', fr: 'Ain Raggada', aliases: ['ain raggada'] },
  { ar: 'لݣفيفات', fr: 'Lagfifat', aliases: ['lagfifat'] },
  { ar: 'واد زم', fr: 'Oued Zem', aliases: ['oued zem'] },
  { ar: 'أولاد عياد', fr: 'Ouled Ayad', aliases: ['ouled ayad'] },
  { ar: 'طرفاية', fr: 'Tarfaya', aliases: ['tarfaya'] },
  { ar: 'إتزر', fr: 'Itzer', aliases: ['itzer'] },
  { ar: 'بلفاع', fr: 'Belfaa', aliases: ['belfaa'] },
  { ar: 'زبزات', fr: 'Zebzat', aliases: ['zebzat'] },
  { ar: 'النواصر', fr: 'Nouaceur', aliases: ['nouaceur'] },
  { ar: 'البروج', fr: 'Elbrouj', aliases: ['elbrouj'] },
  { ar: 'بني أنصار', fr: 'Beni Ensar', aliases: ['beni ensar'] },
  { ar: 'تاملالت', fr: 'Tamelalt', aliases: ['tamelalt'] },
  { ar: 'أولاد حسون', fr: 'Oulad Hassoune', aliases: ['oulad hassoune'] },
  { ar: 'العروي', fr: 'Al Aaroui', aliases: ['al aaroui'] },
  { ar: 'أزلا', fr: 'Azla', aliases: ['azla'] },
  { ar: 'أزمور', fr: 'Azemmour', aliases: ['azemmour'] },
  { ar: 'سيدي بنور', fr: 'Sidi Bennour', aliases: ['sidi bennour'] },
  { ar: 'سيدي يحيى زعير', fr: 'Sidi Yahya Zaer', aliases: ['sidi yahya zaer'] },
  { ar: 'أولاد يوسف', fr: 'Oulad Youssef', aliases: ['oulad youssef'] },
  { ar: 'سيدي جابر', fr: 'Sidi Jaber', aliases: ['sidi jaber'] },
  { ar: 'دلالحة', fr: 'Dlalha', aliases: ['dlalha'] },
  { ar: 'أولاد يحيى', fr: 'Oulad Yahya', aliases: ['oulad yahya'] },
  { ar: 'السمارة', fr: 'Essamara', aliases: ['essamara'] },
  { ar: 'بويزكارن', fr: 'Bouizakarne', aliases: ['bouizakarne'] },
  { ar: 'رانات', fr: 'Ranat', aliases: ['ranat'] },
  { ar: 'حد خاموجة', fr: 'Had Khamouja', aliases: ['had khamouja'] },
  { ar: 'الحسيمة', fr: 'Al Hoceima', aliases: ['al hoceima'] },
  { ar: 'عين الشعير', fr: 'Ain Chair', aliases: ['ain chair'] },
  { ar: 'وارݣي', fr: 'Ouargui', aliases: ['ouargui'] },
  { ar: 'أدوز', fr: 'Adouz', aliases: ['adouz'] },
  { ar: 'غرم العلام', fr: 'Ghorm Elam', aliases: ['ghorm elam'] },
  { ar: 'أكدز', fr: 'Agdz', aliases: ['agdz'] },
  { ar: 'الݣارة', fr: 'El Gara', aliases: ['el gara'] },
  { ar: 'عين شݣاݣ', fr: 'Ain Cheggag', aliases: ['ain cheggag'] },
  { ar: 'قلعة السراغنة', fr: 'Kelaa Des Sraghna', aliases: ['kelaa des sraghna'] },
  { ar: 'كوكي', fr: 'Koki', aliases: ['koki'] },
  { ar: 'الحاجب', fr: 'El Hajeb', aliases: ['el hajeb'] },
  { ar: 'المضيق', fr: 'Mdiq', aliases: ['mdiq'] },
  { ar: 'آيت موسى', fr: 'Ait Moussa', aliases: ['ait moussa'] },
  { ar: 'تامنصورت', fr: 'Tamansourt', aliases: ['tamansourt'] },
  { ar: 'تارݣيست - الحسيمة', fr: 'Targuist - Al Hoceima', aliases: ['targuist al hoceima'] },
  { ar: 'الرواضي', fr: 'Rwadi', aliases: ['rwadi'] },
  { ar: 'تندرارة', fr: 'Tendrara', aliases: ['tendrara'] },
  { ar: 'أنزا', fr: 'Anza', aliases: ['anza'] },
  { ar: 'تويمة', fr: 'Touima', aliases: ['touima'] },
  { ar: 'عين عتيق', fr: 'Ain Atiq', aliases: ['ain atiq'] },
  { ar: 'باب تازة', fr: 'Bab Taza', aliases: ['bab taza'] },
  { ar: 'فم العنصر', fr: 'Foum El Ansar', aliases: ['foum el ansar'] },
  { ar: 'بوجدور', fr: 'Boujdour', aliases: ['boujdour'] },
  { ar: 'سطات', fr: 'Settat', aliases: ['settat'] },
  { ar: 'إمجاض', fr: 'Imjad', aliases: ['imjad'] },
  { ar: 'تنغير', fr: 'Tinghir', aliases: ['tinghir'] },
  { ar: 'تغسالين', fr: 'Tighssaline', aliases: ['tighssaline'] },
  { ar: 'تارودانت-إغرم', fr: 'Taroudant-Ighrem', aliases: ['taroudant ighrem'] },
  { ar: 'بني شيكر', fr: 'Beni Chiker', aliases: ['beni chiker'] },
  { ar: 'أكليم', fr: 'Aklim', aliases: ['aklim'] },
  { ar: 'الدويات', fr: 'Douyet', aliases: ['douyet'] },
  { ar: 'أولاد عياش', fr: 'Oulad Yaich', aliases: ['oulad yaich'] },
  { ar: 'السعيدية', fr: 'Saidia', aliases: ['saidia'] },
  { ar: 'أولاد رحو', fr: 'Oulad Rehou', aliases: ['oulad rehou'] },
  { ar: 'تاراست', fr: 'Tarrast', aliases: ['tarrast'] },
  { ar: 'أسني', fr: 'Asni', aliases: ['asni'] },
  { ar: 'سيدي حجاج', fr: 'Sidi Hajjaj', aliases: ['sidi hajjaj'] },
  { ar: 'أكارد', fr: 'Agard', aliases: ['agard'] },
  { ar: 'الويدان', fr: 'El-Ouidane', aliases: ['el ouidane'] },
  { ar: 'مولاي عبد الله', fr: 'Moulay Abdellah', aliases: ['moulay abdellah'] },
  { ar: 'تݣزيرت', fr: 'Tagzert', aliases: ['tagzert'] },
  { ar: 'بني درار', fr: 'Beni Drar', aliases: ['beni drar'] },
  { ar: 'شيشاوة', fr: 'Chichaoua', aliases: ['chichaoua'] },
  { ar: 'أولاد برحيل', fr: 'Ouled Berhil', aliases: ['ouled berhil'] },
  { ar: 'سيدي يحيى الغرب', fr: 'Sidi Yahya Du Rharb', aliases: ['sidi yahya du rharb'] },
  { ar: 'سلوان', fr: 'Selouane', aliases: ['selouane'] },
  { ar: 'دار ولد زيدوح', fr: 'Dar Ould Zidouh', aliases: ['dar ould zidouh'] },
  { ar: 'مولاي يعقوب', fr: 'Moulay Yacoub', aliases: ['moulay yacoub'] },
  { ar: 'أݣلموس', fr: 'Aguelmous', aliases: ['aguelmous'] },
  { ar: 'تين منصور', fr: 'Tin Mansour', aliases: ['tin mansour'] },
  { ar: 'حد السوالم', fr: 'Had Soualem', aliases: ['had soualem'] },
  { ar: 'اثنين الغربية', fr: 'Tnin Gharbia', aliases: ['tnin gharbia'] },
  { ar: 'سوق الخميس الساحل', fr: 'Souk Khemis Du Sahel', aliases: ['souk khemis du sahel'] },
  { ar: 'بومية', fr: 'Boumia', aliases: ['boumia'] },
  { ar: 'عين الشقف', fr: 'Ain Chqef', aliases: ['ain chqef'] },
  { ar: 'سوق السبت', fr: 'Souk Sebt', aliases: ['souk sebt'] },
  { ar: 'اثنين شتوكة', fr: 'Tnin Chtouka', aliases: ['tnin chtouka'] },
  { ar: 'سيدي رحال', fr: 'Sidi Rahal', aliases: ['sidi rahal'] },
  { ar: 'ثلاث بوݣدرة', fr: 'Tlat Bougedra', aliases: ['tlat bougedra'] },
  { ar: 'بني تجيت', fr: 'Bni Tadjite', aliases: ['bni tadjite'] },
  { ar: 'أوريكا', fr: 'Ourika', aliases: ['ourika'] },
  { ar: 'تحناوت', fr: 'Tahannaout', aliases: ['tahannaout'] },
  { ar: 'مريرت', fr: 'Mrirt', aliases: ['mrirt'] },
  { ar: 'سيدي زوين', fr: 'Sidi Zouine', aliases: ['sidi zouine'] },
  { ar: 'أولاد فرج', fr: 'Oulad Frej', aliases: ['oulad frej'] },
  { ar: 'ملوسة', fr: 'Melloussa', aliases: ['melloussa'] },
  { ar: 'إدلسان', fr: 'Idalsan', aliases: ['idalsan'] },
  { ar: 'آيت إسحاق', fr: 'Ait Ishaq', aliases: ['ait ishaq'] },
  { ar: 'تامراغت', fr: 'Tamraght', aliases: ['tamraght'] },
  { ar: 'أورير', fr: 'Aourir', aliases: ['aourir'] },
  { ar: 'تمارة', fr: 'Temara', aliases: ['temara'] },
  { ar: 'امحايا', fr: 'M\'Haya', aliases: ['m haya'] },
  { ar: 'عين العودة', fr: 'Ain El Aouda', aliases: ['ain el aouda'] },
  { ar: 'بن يخلف', fr: 'Ben Yakhlef', aliases: ['ben yakhlef'] },
  { ar: 'بن الطيب', fr: 'Ben Taieb', aliases: ['ben taieb'] },
  { ar: 'سيدي حماد', fr: 'Sidi Hmad', aliases: ['sidi hmad'] },
  { ar: 'القليعة', fr: 'Leqliaa', aliases: ['leqliaa'] },
  { ar: 'قبيلة', fr: 'Kabila', aliases: ['kabila'] },
  { ar: 'أولاد الطيب', fr: 'Ouled Tayeb', aliases: ['ouled tayeb'] },
  { ar: 'سوق الأربعاء الغرب', fr: 'Souk El Arbaa Du Gharb', aliases: ['souk el arbaa du gharb'] },
  { ar: 'سيدي بيبي', fr: 'Sidi Bibi', aliases: ['sidi bibi'] },
  { ar: 'مجاط', fr: 'Mejjat', aliases: ['mejjat'] },
  { ar: 'زاوية سيدي سماعيل', fr: 'Zaouyat Sidi Smail', aliases: ['zaouyat sidi smail'] },
  { ar: 'تاهلة', fr: 'Tahla', aliases: ['tahla'] },
  { ar: 'ميدلت', fr: 'Midelt', aliases: ['midelt'] },
  { ar: 'أفورار', fr: 'Afourar', aliases: ['afourar'] },
  { ar: 'عين الركادة', fr: 'Ain Erreggada', aliases: ['ain erreggada'] },
  { ar: 'هرهورة', fr: 'Harhoura', aliases: ['harhoura'] },
  { ar: 'دريوش', fr: 'Driouch', aliases: ['driouch'] },
  { ar: 'سيدي عيسى بن علي', fr: 'Sidi Aissa Ben Ali', aliases: ['sidi aissa ben ali'] },
  { ar: 'الشماعية', fr: 'Echemmaia', aliases: ['echemmaia'] },
  { ar: 'بوكيدان - الحسيمة', fr: 'Boukidan - Al Hoceima', aliases: ['boukidan al hoceima'] },
  { ar: 'أكويم', fr: 'Agouim', aliases: ['agouim'] },
  { ar: 'تمنار', fr: 'Tamanar', aliases: ['tamanar'] },
  { ar: 'أولوز', fr: 'Aoulouz', aliases: ['aoulouz'] },
  { ar: 'العطاوية', fr: 'El Attaouia', aliases: ['el attaouia'] },
  { ar: 'زرايبات', fr: 'Zraibat', aliases: ['zraibat'] },
  { ar: 'عين الصفا', fr: 'Ain Assafa', aliases: ['ain assafa'] },
  { ar: 'تيزنيت', fr: 'Tiznit', aliases: ['tiznit'] },
  { ar: 'بوجنيبة', fr: 'Boujniba', aliases: ['boujniba'] },
  { ar: 'أولاد سعيد الواد', fr: 'Ouled Said El Oued', aliases: ['ouled said el oued'] },
  { ar: 'مولاي عبد الله أمغار', fr: 'Moullay Abdellah Amghar', aliases: ['moullay abdellah amghar'] },
  { ar: 'أوناغة', fr: 'Ounagha', aliases: ['ounagha'] },
  { ar: 'الداخلة', fr: 'Dakhla', aliases: ['dakhla'] },
  { ar: 'المهدية', fr: 'Mehdia', aliases: ['mehdia'] },
  { ar: 'دردارة', fr: 'Derdara', aliases: ['derdara'] },
  { ar: 'واد الجديدة', fr: 'Oued Jdida', aliases: ['oued jdida'] },
  { ar: 'مصمودة', fr: 'Masmouda', aliases: ['masmouda'] },
  { ar: 'الدراركة', fr: 'Drarga', aliases: ['drarga'] },
  { ar: 'تساوت', fr: 'Tassaout', aliases: ['tassaout'] },
  { ar: 'قرية با محمد', fr: 'Karia Ba Mohamed', aliases: ['karia ba mohamed'] },
  { ar: 'تازناخت', fr: 'Tazenakht', aliases: ['tazenakht'] },
  { ar: 'الرماني', fr: 'Rommani', aliases: ['rommani'] },
  { ar: 'سطات - سيدي حجاج', fr: 'Settat - Sidi Hajaj', aliases: ['settat sidi hajaj'] },
  { ar: 'تامايت', fr: 'Tamait', aliases: ['tamait'] },
  { ar: 'زاكورة', fr: 'Zagora', aliases: ['zagora'] },
  { ar: 'سيدي حجاج', fr: 'Sidi Hajaj', aliases: ['sidi hajaj'] },
  { ar: 'إيمي وادار', fr: 'Imi Ouaddar', aliases: ['imi ouaddar'] },
  { ar: 'ݣزناية', fr: 'Gzenaya', aliases: ['gzenaya'] },
  { ar: 'آيت أورير', fr: 'Ait Ourir', aliases: ['ait ourir'] },
  { ar: 'المجاعرة', fr: 'Lamjaara', aliases: ['lamjaara'] },
  { ar: 'زومي', fr: 'Zoumi', aliases: ['zoumi'] },
  { ar: 'ستيحات', fr: 'Stehat', aliases: ['stehat'] },
  { ar: 'سيدي رضوان', fr: 'Sidi Redouane', aliases: ['sidi redouane'] },
  { ar: 'خميس الرميلة', fr: 'Khmis Rmila', aliases: ['khmis rmila'] },
  { ar: 'تاملوحت', fr: 'Tamesluht', aliases: ['tamesluht'] },
  { ar: 'العوامرة', fr: 'Laaouamera', aliases: ['laaouamera'] },
  { ar: 'واد لاو', fr: 'Oued Laou', aliases: ['oued laou'] },
  { ar: 'تاغبالت', fr: 'Taghbalt', aliases: ['taghbalt'] },
  { ar: 'سيدي بوصبر', fr: 'Sidi Bousber', aliases: ['sidi bousber'] },
  { ar: 'القصر الكبير', fr: 'Ksar El Kebir', aliases: ['ksar el kebir'] },
  { ar: 'شفشاون', fr: 'Chefchaouen', aliases: ['chefchaouen'] },
  { ar: 'تروال', fr: 'Teroual', aliases: ['teroual'] },
  { ar: 'بوعسيدة', fr: 'Bouaassida', aliases: ['bouaassida'] },
  { ar: 'دالية', fr: 'Dalia', aliases: ['dalia'] },
  { ar: 'تاماريس', fr: 'Tamaris', aliases: ['tamaris'] },
  { ar: 'تافتاشت', fr: 'Tafetachte', aliases: ['tafetachte'] },
  { ar: 'الجبهة', fr: 'El Jebha', aliases: ['el jebha'] },
  { ar: 'مرزوكة', fr: 'Merzouga', aliases: ['merzouga'] },
  { ar: 'آيت عيسى', fr: 'Ait Aissa', aliases: ['ait aissa'] },
  { ar: 'سيدي علال التازي', fr: 'Sidi Allal Tazi', aliases: ['sidi allal tazi'] },
  { ar: 'زاودة', fr: 'Zaouda', aliases: ['zaouda'] },
  { ar: 'عين حرودة', fr: 'Ain Harrouda', aliases: ['ain harrouda'] },
  { ar: 'تافراوت', fr: 'Tafraoute', aliases: ['tafraoute'] },
  { ar: 'الريصاني', fr: 'Rissani', aliases: ['rissani'] },
  { ar: 'آيت عمو', fr: 'Ait Amou', aliases: ['ait amou'] },
  { ar: 'بوعرفة', fr: 'Bouarfa', aliases: ['bouarfa'] },
  { ar: 'مقريصات', fr: 'Mokrisset', aliases: ['mokrisset'] },
  { ar: 'ونانة', fr: 'Ounnana', aliases: ['ounnana'] },
  { ar: 'جرف الملحة', fr: 'Jourf El Melha', aliases: ['jourf el melha'] },
  { ar: 'بوقرة', fr: 'Bouqorra', aliases: ['bouqorra'] },
  { ar: 'تنجداد', fr: 'Tinjdad', aliases: ['tinjdad'] },
  { ar: 'جرف الملحة', fr: 'Jarf Malha', aliases: ['jarf malha'] },
  { ar: 'سيدي سليمان', fr: 'Sidi Sliman', aliases: ['sidi sliman'] },
  { ar: 'بني أحمد', fr: 'Bni Ahmed', aliases: ['bni ahmed'] },
  { ar: 'كلميمة', fr: 'Goulmima', aliases: ['goulmima'] },
  { ar: 'إدلسان', fr: 'Idelsane', aliases: ['idelsane'] },
  { ar: 'بريكشة', fr: 'Brikchia', aliases: ['brikchia'] },
  { ar: 'دار الݣداري', fr: 'Dar Guedari', aliases: ['dar guedari'] },
  { ar: 'طاطا', fr: 'Tata', aliases: ['tata'] },
  { ar: 'مقريصات', fr: 'Moqrisst', aliases: ['moqrisst'] },
  { ar: 'أسا الزاݣ', fr: 'Assa-Zag', aliases: ['assa zag'] },
  { ar: 'المدينة الجديدة', fr: 'Madina Jedida', aliases: ['madina jedida'] },
  { ar: 'أوطاط الحاج', fr: 'Outat El Haj', aliases: ['outat el haj'] },
  { ar: 'عين البيضاء', fr: 'Ain Beida', aliases: ['ain beida'] },
];
