import {
  Bot, MessageCircle, Truck, BarChart3, ShoppingBag, Wrench, Calendar,
  Store, Globe, Gift, Image as ImageIcon, Languages, type LucideIcon,
} from 'lucide-react';
import type { Lang } from '../../i18n/translations';

// ── الأنواع ──────────────────────────────────────────────
export type Stats = {
  merchants: number; products: number; services: number; orders: number; listings: number;
  cities: { city: string; count: number }[];
};
export type Listing = {
  id: string; type?: string; name: string; price: number; city?: string;
  images?: string[]; sellerName?: string; ratingAvg?: number; emoji?: string; sample?: boolean;
};
export type Cap = { Icon: LucideIcon; k: string; c: string; feat?: boolean; wide?: boolean };

// ── القاموس الأساسي (المحتوى المترجم مسبقاً) ──────────────
export const L: Record<Lang, Record<string, string>> = {
  ar: {
    market: '🏪 السوق', login: 'دخول', dashboard: 'لوحة التحكم', browseMarket: '🏪 تصفّح السوق',
    heroNote: 'مجاني للأبد · بدون بطاقة بنكية · جاهز في 5 دقائق', seeHow: 'شاهد كيف يعمل', scrollHint: 'اكتشف المزيد',
    capTitle: 'كل ما تحتاجه في تطبيق واحد', capSub: 'قول حاجتك بالدارجة، وأمانزين يفهمك ويوصّلك لأوّل خطوة — بلا ما تعرف منين تبدا.',
    'cap.products': 'المنتجات', 'cap.products.d': 'أضف منتجاتك بصور وفيديو وخيارات (مقاس/لون) ووصف يكتبه الذكاء الاصطناعي.',
    'cap.services': 'الخدمات', 'cap.services.d': 'قدّم خدماتك مع حجز موعد، طلب عادي، أو طلب عاجل — ومعرض أعمالك.',
    'cap.bookings': 'المواعيد والحجوزات', 'cap.bookings.d': 'استقبل المواعيد بالتاريخ والساعة، أو التدخلات الاستعجالية الفورية.',
    'cap.store': 'متجرك الإلكتروني', 'cap.store.d': 'متجر أنيق برابط خاص بك — تشاركه وتستقبل الطلبات فوراً.',
    'cap.market': 'السوق الموحّد', 'cap.market.d': 'انشر إعلاناتك في السوق المغربي الموحّد وابلغ آلاف الزبائن الجدد.',
    'cap.ai': 'الذكاء الاصطناعي', 'cap.ai.d': 'مساعد يرد على الزبائن، يقترح المنتجات، ويجمع بيانات الطلب 24/7.',
    'cap.messages': 'الرسائل الموحّدة', 'cap.messages.d': 'واتساب وفيسبوك وإنستغرام في صندوق واحد — لا تفوّت أي رسالة.',
    'cap.delivery': 'التوصيل والتتبع', 'cap.delivery.d': 'اربط شركات التوصيل، أرسل الشحنات تلقائياً، وتتبّعها لحظة بلحظة.',
    'cap.coupons': 'الكوبونات وعجلة الحظ', 'cap.coupons.d': 'أنشئ أكواد خصم، برامج ولاء، وعجلة حظ تزيد تفاعل زبائنك.',
    'cap.analytics': 'التحليلات', 'cap.analytics.d': 'تابع الزيارات والمبيعات والأرباح ومصادر الزوار بأرقام حيّة.',
    'cap.banner': 'استوديو البانر', 'cap.banner.d': 'صمّم بانرات وإعلانات احترافية بالذكاء الاصطناعي وانشرها بضغطة.',
    'cap.langs': 'متعدّد اللغات', 'cap.langs.d': 'متجرك بخمس لغات: العربية، الدارجة، الفرنسية، الإنجليزية، والصينية.',
    howTitle: 'كيف يعمل؟', howSub: 'ثلاث خطوات من حاجتك إلى أوّل خطوة واضحة',
    how1d: 'قول آش واقع بالدارجة — حتى كلمة وحدة تكفي. أمانزين يفهمك.',
    how2d: 'أمانزين يوصّلك للمختصّ المناسب قريب منك — بلا ما تعرف منين تبدا.',
    how3d: 'تواصل، احجز، وسيّر حاجتك من أوّلها لآخرها — فبلاصة وحدة.',
    ctaTitle: 'حاجتك على بُعد جملة', ctaSub: 'قول آش واقع — وأمانزين يوجّهك لأوّل خطوة. بلا تسجيل باش تجرّب.',
    footTagline: 'منصّة المغرب الذكية للبيع والخدمات والحجوزات', footRights: 'كل الحقوق محفوظة', creditPrefix: 'تطوير',
  },
  darija: {
    market: '🏪 السوق', login: 'دخول', dashboard: 'لوحة التحكم', browseMarket: '🏪 تصفّح السوق',
    heroNote: 'مجاني للأبد · بلا كارط بانكير · واجد ف 5 دقايق', seeHow: 'شوف كيفاش خدّام', scrollHint: 'كتشف كثر',
    capTitle: 'كل ما تحتاجو ف تطبيق واحد', capSub: 'قول حاجتك بالدارجة، وأمانزين يفهمك ويوصّلك لأوّل خطوة — بلا ما تعرف منين تبدا.',
    'cap.products': 'المنتجات', 'cap.products.d': 'زيد منتجاتك بصور وفيديو وخيارات (قياس/لون) ووصف كيكتبو الذكاء الاصطناعي.',
    'cap.services': 'الخدمات', 'cap.services.d': 'قدّم خدماتك مع حجز موعد، طلب عادي، ولا طلب مستعجل — ومعرض ديال خدماتك.',
    'cap.bookings': 'المواعيد والحجوزات', 'cap.bookings.d': 'استقبل المواعيد بالتاريخ والساعة، ولا التدخلات المستعجلة دغيا.',
    'cap.store': 'متجرك الإلكتروني', 'cap.store.d': 'متجر شيك برابط ديالك — تشاركو وتستقبل الطلبات دغيا.',
    'cap.market': 'السوق الموحّد', 'cap.market.d': 'نشر إعلاناتك ف السوق المغربي الموحّد وابلغ آلاف الزبناء الجداد.',
    'cap.ai': 'الذكاء الاصطناعي', 'cap.ai.d': 'مساعد كيجاوب الزبناء، كيقترح المنتجات، وكيجمع بيانات الطلب 24/7.',
    'cap.messages': 'الرسائل الموحّدة', 'cap.messages.d': 'واتساب وفيسبوك وإنستغرام ف صندوق واحد — ماتفوّت حتى رسالة.',
    'cap.delivery': 'التوصيل والتتبع', 'cap.delivery.d': 'ربط شركات التوصيل، صيفط الشحنات أوتوماتيك، وتبّعها لحظة بلحظة.',
    'cap.coupons': 'الكوبونات وعجلة الحظ', 'cap.coupons.d': 'دير أكواد تخفيض، برامج ولاء، وعجلة حظ كتزيد تفاعل زبناءك.',
    'cap.analytics': 'التحليلات', 'cap.analytics.d': 'تبّع الزيارات والمبيعات والأرباح ومصادر الزوار بأرقام حية.',
    'cap.banner': 'استوديو البانر', 'cap.banner.d': 'صمّم بانرات وإعلانات احترافية بالذكاء الاصطناعي ونشرها بضغطة.',
    'cap.langs': 'متعدّد اللغات', 'cap.langs.d': 'متجرك بخمس لغات: العربية، الدارجة، الفرنسية، الإنجليزية، والصينية.',
    howTitle: 'كيفاش خدّام؟', howSub: 'ثلاثة خطوات من حاجتك حتى أوّل خطوة واضحة',
    how1d: 'قول آش واقع بالدارجة — حتى كلمة وحدة كافية. أمانزين كيفهمك.',
    how2d: 'أمانزين كيوصّلك للمختصّ المناسب قريب منك — بلا ما تعرف منين تبدا.',
    how3d: 'تواصل، احجز، وسيّر حاجتك من لُوّلها للُخّرها — فبلاصة وحدة.',
    ctaTitle: 'حاجتك على بُعد جملة', ctaSub: 'قول آش واقع — وأمانزين يوجّهك لأوّل خطوة. بلا تسجيل باش تجرّب.',
    footTagline: 'منصة المغرب الذكية للبيع والخدمات والحجوزات', footRights: 'كل الحقوق محفوظة', creditPrefix: 'تطوير',
  },
  fr: {
    market: '🏪 Le Souk', login: 'Connexion', dashboard: 'Tableau de bord', browseMarket: '🏪 Explorer Le Souk',
    heroNote: 'Gratuit à vie · Sans carte bancaire · Prêt en 5 min', seeHow: 'Voir comment ça marche', scrollHint: 'Découvrir plus',
    capTitle: 'Tout ce qu’il vous faut dans une seule app', capSub: 'Une plateforme complète qui gère votre commerce de A à Z — produits, services, réservations, souk, livraison et IA.',
    'cap.products': 'Produits', 'cap.products.d': 'Ajoutez vos produits avec photos, vidéo, options (taille/couleur) et descriptions générées par l’IA.',
    'cap.services': 'Services', 'cap.services.d': 'Proposez vos services : rendez-vous, demande simple ou urgente — et votre portfolio.',
    'cap.bookings': 'Rendez-vous & Réservations', 'cap.bookings.d': 'Recevez des rendez-vous par date et heure, ou des interventions urgentes immédiates.',
    'cap.store': 'Votre boutique en ligne', 'cap.store.d': 'Une boutique élégante avec votre propre lien — partagez et recevez les commandes aussitôt.',
    'cap.market': 'Le Souk unifié', 'cap.market.d': 'Publiez vos annonces sur Le Souk marocain unifié et touchez des milliers de nouveaux clients.',
    'cap.ai': 'Intelligence artificielle', 'cap.ai.d': 'Un assistant qui répond aux clients, suggère des produits et collecte les commandes 24/7.',
    'cap.messages': 'Messagerie unifiée', 'cap.messages.d': 'WhatsApp, Facebook et Instagram dans une seule boîte — ne ratez aucun message.',
    'cap.delivery': 'Livraison & Suivi', 'cap.delivery.d': 'Connectez les transporteurs, expédiez automatiquement et suivez en temps réel.',
    'cap.coupons': 'Coupons & Roue de la chance', 'cap.coupons.d': 'Créez des codes promo, des programmes de fidélité et une roue de la chance.',
    'cap.analytics': 'Analytique', 'cap.analytics.d': 'Suivez visites, ventes, bénéfices et sources de trafic en temps réel.',
    'cap.banner': 'Studio de bannières', 'cap.banner.d': 'Créez des bannières et publicités professionnelles avec l’IA, en un clic.',
    'cap.langs': 'Multilingue', 'cap.langs.d': 'Votre boutique en 5 langues : arabe, darija, français, anglais et chinois.',
    howTitle: 'Comment ça marche ?', howSub: 'Trois étapes simples, de zéro à votre première vente',
    how1d: 'Inscrivez-vous gratuitement et ajoutez vos produits et services en quelques minutes — sans compétences techniques.',
    how2d: 'Recevez commandes, réservations et messages, et laissez l’IA répondre à vos clients automatiquement.',
    how3d: 'Livrez dans toutes les villes du Maroc avec suivi automatique, et encaissez à la livraison.',
    ctaTitle: 'Votre boutique intelligente à quelques minutes', ctaSub: 'Commencez gratuitement aujourd’hui — sans carte bancaire ni engagement.',
    footTagline: 'La plateforme marocaine intelligente pour la vente, les services et les réservations', footRights: 'Tous droits réservés', creditPrefix: 'Développé par',
  },
  en: {
    market: '🏪 Market', login: 'Sign in', dashboard: 'Dashboard', browseMarket: '🏪 Browse the market',
    heroNote: 'Free forever · No credit card · Ready in 5 minutes', seeHow: 'See how it works', scrollHint: 'Discover more',
    capTitle: 'Everything you need in one app', capSub: 'A complete platform that runs your business end to end — products, services, bookings, marketplace, delivery and AI.',
    'cap.products': 'Products', 'cap.products.d': 'Add products with photos, video, options (size/color) and AI-written descriptions.',
    'cap.services': 'Services', 'cap.services.d': 'Offer services with appointment, standard or urgent request — plus your portfolio.',
    'cap.bookings': 'Appointments & Bookings', 'cap.bookings.d': 'Take appointments by date and time, or instant urgent interventions.',
    'cap.store': 'Your online store', 'cap.store.d': 'A sleek store with your own link — share it and receive orders instantly.',
    'cap.market': 'Unified marketplace', 'cap.market.d': 'Post your ads on the unified Moroccan Market and reach thousands of new customers.',
    'cap.ai': 'Artificial intelligence', 'cap.ai.d': 'An assistant that answers customers, suggests products and collects orders 24/7.',
    'cap.messages': 'Unified inbox', 'cap.messages.d': 'WhatsApp, Facebook and Instagram in one inbox — never miss a message.',
    'cap.delivery': 'Delivery & Tracking', 'cap.delivery.d': 'Connect couriers, ship automatically and track in real time.',
    'cap.coupons': 'Coupons & Lucky wheel', 'cap.coupons.d': 'Create discount codes, loyalty programs and a lucky wheel to boost engagement.',
    'cap.analytics': 'Analytics', 'cap.analytics.d': 'Track visits, sales, profits and traffic sources with live numbers.',
    'cap.banner': 'Banner studio', 'cap.banner.d': 'Design professional banners and ads with AI and publish in one click.',
    'cap.langs': 'Multilingual', 'cap.langs.d': 'Your store in 5 languages: Arabic, Darija, French, English and Chinese.',
    howTitle: 'How it works', howSub: 'Three simple steps from zero to your first sale',
    how1d: 'Sign up free and add your products and services in minutes — no technical skills needed.',
    how2d: 'Receive orders, bookings and messages, and let the AI reply to your customers automatically.',
    how3d: 'Deliver to every Moroccan city with automatic tracking, and get paid on delivery.',
    ctaTitle: 'Your smart store is minutes away', ctaSub: 'Start free today — no credit card, no commitment.',
    footTagline: 'Morocco’s smart platform for selling, services and bookings', footRights: 'All rights reserved', creditPrefix: 'Developed by',
  },
  zh: {
    market: '🏪 市场', login: '登录', dashboard: '控制台', browseMarket: '🏪 浏览市场',
    heroNote: '永久免费 · 无需银行卡 · 5 分钟搞定', seeHow: '看看如何运作', scrollHint: '了解更多',
    capTitle: '一个应用，满足全部需求', capSub: '端到端运营你业务的完整平台 — 产品、服务、预约、市场、配送与 AI。',
    'cap.products': '产品', 'cap.products.d': '添加带照片、视频、选项（尺寸/颜色）和 AI 撰写描述的产品。',
    'cap.services': '服务', 'cap.services.d': '提供服务：预约、普通申请或紧急申请 — 以及你的作品集。',
    'cap.bookings': '预约与预定', 'cap.bookings.d': '按日期和时间接受预约，或即时紧急上门。',
    'cap.store': '你的在线店铺', 'cap.store.d': '拥有专属链接的精美店铺 — 分享即可即时接单。',
    'cap.market': '统一市场', 'cap.market.d': '在统一的摩洛哥市场发布广告，触达数千新客户。',
    'cap.ai': '人工智能', 'cap.ai.d': '全天候回复客户、推荐产品并收集订单的智能助手。',
    'cap.messages': '统一收件箱', 'cap.messages.d': 'WhatsApp、Facebook 和 Instagram 集于一个收件箱 — 不漏任何消息。',
    'cap.delivery': '配送与追踪', 'cap.delivery.d': '连接快递、自动发货并实时追踪。',
    'cap.coupons': '优惠券与幸运转盘', 'cap.coupons.d': '创建折扣码、会员计划和幸运转盘，提升互动。',
    'cap.analytics': '数据分析', 'cap.analytics.d': '用实时数据追踪访问、销售、利润和流量来源。',
    'cap.banner': '横幅工作室', 'cap.banner.d': '用 AI 一键设计并发布专业横幅和广告。',
    'cap.langs': '多语言', 'cap.langs.d': '你的店铺支持 5 种语言：阿拉伯语、达里贾语、法语、英语和中文。',
    howTitle: '如何运作', howSub: '三个简单步骤，从零到第一笔订单',
    how1d: '免费注册，几分钟内添加你的产品和服务 — 无需任何技术。',
    how2d: '接收订单、预约和消息，让 AI 助手自动回复你的客户。',
    how3d: '配送至摩洛哥所有城市，自动追踪，货到收款。',
    ctaTitle: '你的智能店铺，几分钟即可拥有', ctaSub: '今天免费开始 — 无需银行卡，无任何约束。',
    footTagline: '摩洛哥智能销售、服务与预约平台', footRights: '版权所有', creditPrefix: '开发',
  },
};

// ── قاموس المحتوى الجديد (يشمل أقسام FAQ/Promo/الثقة/الفوتر) ──
export const LX: Record<Lang, Record<string, string>> = {
  ar: {
    osBadge: 'كل كلمة عندها طريق', sample: 'مثال', byStore: 'بواسطة', dh: 'د.م.',
    liveTitle: '🛍️ منتجات وخدمات حيّة من السوق', liveSub: 'إعلانات حقيقية نشرها تجّار AMANZINE الآن', liveSampleSub: 'أمثلة توضيحيّة — السوق كيتعمّر دابا. كون نتَ الأوّل.', liveViewAll: 'تصفّح كل السوق',
    citiesTitle: 'متاجر في كل المغرب', citiesSub: 'تجّار ينمّون أعمالهم من كل المدن', cityUnit: 'إعلان', cityBeFirst: 'كن الأول هنا',
    statMerchants: 'تاجر', statProducts: 'منتج', statOrders: 'طلب', statListings: 'إعلان في السوق',
    earlyBadge: '🚀 منصّة جديدة في الانطلاق', earlyTitle: 'كن من أوائل التجّار في AMANZINE', earlySub: 'نبني السوق المغربي الذكي معاً من البداية — مكانك في المقدّمة محجوز الآن.',
    bentoTitle: 'منظومة تجارة كاملة', bentoSub: 'كل أدوات نجاحك في مكان واحد — والذكاء الاصطناعي يدعمها لا يحلّ محلّها.',
    storesTitle: '⭐ لماذا التجّار يختارون AMANZINE', previewHint: 'هكذا يبدو متجرك',
    why1: 'إطلاق في دقائق', why1d: 'متجر جاهز برابط خاص دون أي خبرة تقنية.',
    why2: 'يعمل 24/7', why2d: 'المساعد الذكي يرد ويجمع الطلبات حتى وأنت نائم.',
    why3: 'وصول أوسع', why3d: 'السوق الموحّد + كل قنوات التواصل في مكان واحد.',
    seoTitle: 'AMANZINE — كل كلمة عندها طريق', seoDesc: 'قول حاجتك بالدارجة وأمانزين يفهمك ويوجّهك للمختصّ المناسب قريب منك. كل كلمة عندها طريق.',
    promo: '✨ قول آش واقع… وأمانزين يوجّهك لأوّل خطوة', promoCta: 'جرّب دابا',
    trustSecure: 'آمن 100%', trustFast: 'جاهز في دقائق', trustSupport: 'دعم 24/7',
    faqTitle: 'أسئلة شائعة', faqSub: 'كل ما تحتاج معرفته قبل البدء',
    faqQ1: 'هل يمكنني البدء مجاناً فعلاً؟', faqA1: 'نعم، يمكنك إنشاء متجرك وإضافة منتجاتك مجاناً تماماً وبدون بطاقة بنكية.',
    faqQ2: 'كم يستغرق إنشاء المتجر؟', faqA2: 'يمكنك إنشاء متجرك وإضافة أول منتج في أقل من 5 دقائق، دون أي خبرة تقنية.',
    faqQ3: 'هل المساعد الذكي يفهم الدارجة؟', faqA3: 'نعم، يتفاعل المساعد بالعربية والدارجة والفرنسية والإنجليزية والصينية.',
    faqQ4: 'هل يمكنني الربط مع شركات التوصيل؟', faqA4: 'نعم، تدعم المنصّة ربط شركات التوصيل وإرسال الشحنات وتتبّعها تلقائياً.',
    footExplore: 'استكشف', lnkMarket: 'السوق', lnkPricing: 'الأسعار', lnkHow: 'كيف يعمل', lnkFaq: 'الأسئلة الشائعة', backTop: 'العودة للأعلى',
  },
  darija: {
    osBadge: 'كل كلمة عندها طريق', sample: 'مثال', byStore: 'ديال', dh: 'د.م.',
    liveTitle: '🛍️ منتجات وخدمات حيّة من السوق', liveSub: 'إعلانات حقيقية نشروهم تجّار AMANZINE دابا', liveSampleSub: 'هادو أمثلة — السوق كيتعمّر دابا. كون نتَ الأوّل.', liveViewAll: 'تصفّح السوق كامل',
    citiesTitle: 'متاجر ف كل المغرب', citiesSub: 'تجّار كينمّيو خدمتهم من كل المدن', cityUnit: 'إعلان', cityBeFirst: 'كن الأول هنا',
    statMerchants: 'تاجر', statProducts: 'منتج', statOrders: 'طلب', statListings: 'إعلان ف السوق',
    earlyBadge: '🚀 منصّة جديدة ف الانطلاق', earlyTitle: 'كن من أوائل التجّار ف AMANZINE', earlySub: 'كنبنيو السوق المغربي الذكي مع بعضياتنا من البداية — بلاصتك ف المقدّمة محجوزة دابا.',
    bentoTitle: 'منظومة تجارة كاملة', bentoSub: 'كل أدوات النجاح ف بلاصة وحدة — والذكاء الاصطناعي كيدعمها ماشي كيعوّضها.',
    storesTitle: '⭐ علاش التجّار كيختارو AMANZINE', previewHint: 'هكذا كيبان متجرك',
    why1: 'إطلاق ف دقايق', why1d: 'متجر واجد برابط ديالك بلا أي خبرة تقنية.',
    why2: 'خدّام 24/7', why2d: 'المساعد الذكي كيجاوب وكيجمع الطلبات حتى وانت نعسان.',
    why3: 'وصول كثر', why3d: 'السوق الموحّد + كل قنوات التواصل ف بلاصة وحدة.',
    seoTitle: 'AMANZINE — كل كلمة عندها طريق', seoDesc: 'قول حاجتك بالدارجة وأمانزين يفهمك ويوجّهك للمختصّ المناسب قريب منك. كل كلمة عندها طريق.',
    promo: '🎉 بلاش باش تبدا — دير متجرك اليوم بلا كارط بانكير', promoCta: 'بدا دابا',
    trustSecure: 'آمن 100%', trustFast: 'واجد ف دقايق', trustSupport: 'دعم 24/7',
    faqTitle: 'أسئلة بزّاف مطروحة', faqSub: 'كل ما تحتاج تعرفو قبل ما تبدا',
    faqQ1: 'واش نقدر نبدا بلاش بصح؟', faqA1: 'إيه، تقدر تدير متجرك وتزيد منتجاتك بلاش بالكامل وبلا كارط بانكير.',
    faqQ2: 'شحال كياخد إنشاء المتجر؟', faqA2: 'تقدر دير متجرك وتزيد أول منتج ف أقل من 5 دقايق، بلا أي خبرة تقنية.',
    faqQ3: 'واش المساعد الذكي كيفهم الدارجة؟', faqA3: 'إيه، المساعد كيتواصل بالعربية والدارجة والفرنسية والإنجليزية والصينية.',
    faqQ4: 'واش نقدر نربط مع شركات التوصيل؟', faqA4: 'إيه، المنصّة كتسمح تربط شركات التوصيل وتصيفط الشحنات وتتبّعها أوتوماتيك.',
    footExplore: 'استكشف', lnkMarket: 'السوق', lnkPricing: 'الأثمنة', lnkHow: 'كيفاش خدّام', lnkFaq: 'الأسئلة', backTop: 'العودة للفوق',
  },
  fr: {
    osBadge: 'Need OS · système d’exploitation du besoin', sample: 'Exemple', byStore: 'par', dh: 'DH',
    liveTitle: '🛍️ Produits & services en direct du Souk', liveSub: 'De vraies annonces publiées par les marchands AMANZINE', liveSampleSub: 'Exemples illustratifs — le marché se remplit. Soyez le premier.', liveViewAll: 'Explorer tout le Souk',
    citiesTitle: 'Des boutiques partout au Maroc', citiesSub: 'Des marchands qui se développent dans chaque ville', cityUnit: 'annonces', cityBeFirst: 'Soyez le premier ici',
    statMerchants: 'marchands', statProducts: 'produits', statOrders: 'commandes', statListings: 'annonces au Souk',
    earlyBadge: '🚀 Nouvelle plateforme en lancement', earlyTitle: 'Soyez parmi les premiers marchands AMANZINE', earlySub: 'Construisons ensemble le souk marocain intelligent dès le départ — votre place en tête est réservée maintenant.',
    bentoTitle: 'Un écosystème commerce complet', bentoSub: 'Tous vos outils de réussite au même endroit — l’IA les soutient, sans les remplacer.',
    storesTitle: '⭐ Pourquoi les marchands choisissent AMANZINE', previewHint: 'Voici votre boutique',
    why1: 'Lancement en minutes', why1d: 'Une boutique prête avec votre lien, sans compétences techniques.',
    why2: 'Actif 24/7', why2d: 'L’assistant IA répond et collecte les commandes même la nuit.',
    why3: 'Plus de portée', why3d: 'Le Souk unifié + tous vos canaux au même endroit.',
    seoTitle: 'AMANZINE — le système d’exploitation du besoin, au Maroc', seoDesc: 'Créez votre boutique, proposez vos services et vendez sur le Souk marocain unifié — avec IA et livraison automatique. Gratuit pour démarrer.',
    promo: '🎉 Gratuit pour démarrer — créez votre boutique sans carte bancaire', promoCta: 'Commencer',
    trustSecure: '100% sécurisé', trustFast: 'Prêt en minutes', trustSupport: 'Support 24/7',
    faqTitle: 'Questions fréquentes', faqSub: 'Tout ce qu’il faut savoir avant de commencer',
    faqQ1: 'Puis-je vraiment commencer gratuitement ?', faqA1: 'Oui, créez votre boutique et ajoutez vos produits gratuitement, sans carte bancaire.',
    faqQ2: 'Combien de temps pour créer la boutique ?', faqA2: 'Vous créez votre boutique et ajoutez un premier produit en moins de 5 minutes, sans compétences techniques.',
    faqQ3: 'L’assistant IA comprend-il la darija ?', faqA3: 'Oui, l’assistant échange en arabe, darija, français, anglais et chinois.',
    faqQ4: 'Puis-je connecter des transporteurs ?', faqA4: 'Oui, la plateforme permet de connecter les transporteurs, d’expédier et de suivre automatiquement.',
    footExplore: 'Explorer', lnkMarket: 'Le Souk', lnkPricing: 'Tarifs', lnkHow: 'Comment ça marche', lnkFaq: 'FAQ', backTop: 'Retour en haut',
  },
  en: {
    osBadge: 'Need OS · the operating system for what you need', sample: 'Example', byStore: 'by', dh: 'DH',
    liveTitle: '🛍️ Live products & services from the Market', liveSub: 'Real ads posted by AMANZINE merchants', liveSampleSub: 'Illustrative examples — the market is filling up. Be the first.', liveViewAll: 'Browse the whole market',
    citiesTitle: 'Stores across Morocco', citiesSub: 'Merchants growing in every city', cityUnit: 'ads', cityBeFirst: 'Be the first here',
    statMerchants: 'merchants', statProducts: 'products', statOrders: 'orders', statListings: 'market ads',
    earlyBadge: '🚀 New platform launching', earlyTitle: 'Be among the first AMANZINE merchants', earlySub: 'Let’s build Morocco’s smart marketplace together from day one — your front-row spot is reserved now.',
    bentoTitle: 'A complete commerce ecosystem', bentoSub: 'All your success tools in one place — AI supports them, never replaces them.',
    storesTitle: '⭐ Why merchants choose AMANZINE', previewHint: 'This is how your store looks',
    why1: 'Launch in minutes', why1d: 'A ready store with your own link, no technical skills.',
    why2: 'Always on 24/7', why2d: 'The AI assistant replies and collects orders even while you sleep.',
    why3: 'Wider reach', why3d: 'The unified market + all your channels in one place.',
    seoTitle: 'AMANZINE — the operating system for what you need', seoDesc: 'Create your online store, offer services and sell on Morocco’s unified market — with AI and automatic delivery. Free to start.',
    promo: '🎉 Free to start — create your store today, no credit card', promoCta: 'Start now',
    trustSecure: '100% secure', trustFast: 'Ready in minutes', trustSupport: '24/7 support',
    faqTitle: 'Frequently asked questions', faqSub: 'Everything you need to know before you start',
    faqQ1: 'Can I really start for free?', faqA1: 'Yes — create your store and add products completely free, no credit card required.',
    faqQ2: 'How long does it take to set up?', faqA2: 'You can create your store and add a first product in under 5 minutes, with no technical skills.',
    faqQ3: 'Does the AI assistant understand Darija?', faqA3: 'Yes, the assistant chats in Arabic, Darija, French, English and Chinese.',
    faqQ4: 'Can I connect delivery couriers?', faqA4: 'Yes, the platform connects couriers and ships & tracks shipments automatically.',
    footExplore: 'Explore', lnkMarket: 'Market', lnkPricing: 'Pricing', lnkHow: 'How it works', lnkFaq: 'FAQ', backTop: 'Back to top',
  },
  zh: {
    osBadge: 'Need OS · 需求操作系统', sample: '示例', byStore: '来自', dh: 'DH',
    liveTitle: '🛍️ 来自市场的实时产品与服务', liveSub: 'AMANZINE 商家发布的真实广告', liveViewAll: '浏览整个市场',
    citiesTitle: '遍布摩洛哥的店铺', citiesSub: '在每座城市成长的商家', cityUnit: '条广告', cityBeFirst: '成为这里的第一个',
    statMerchants: '商家', statProducts: '产品', statOrders: '订单', statListings: '市场广告',
    earlyBadge: '🚀 全新平台正在启动', earlyTitle: '成为首批 AMANZINE 商家', earlySub: '从第一天起一起打造摩洛哥智能市场 — 你的前排席位现已为你保留。',
    bentoTitle: '完整的商业生态系统', bentoSub: '所有成功工具集于一处 — AI 是助力，而非替代。',
    storesTitle: '⭐ 商家为何选择 AMANZINE', previewHint: '你的店铺长这样',
    why1: '几分钟上线', why1d: '拥有专属链接的现成店铺，无需技术。',
    why2: '全天候 24/7', why2d: 'AI 助手在你睡觉时也能回复并收集订单。',
    why3: '更广触达', why3d: '统一市场 + 你的所有渠道集于一处。',
    seoTitle: 'AMANZINE — 需求操作系统', seoDesc: '创建在线店铺、提供服务并在摩洛哥统一市场销售 — 配备 AI 与自动配送。免费开始。',
    promo: '🎉 免费开始 — 今天就创建你的店铺，无需银行卡', promoCta: '立即开始',
    trustSecure: '100% 安全', trustFast: '几分钟就绪', trustSupport: '全天候支持',
    faqTitle: '常见问题', faqSub: '开始前你需要了解的一切',
    faqQ1: '我真的可以免费开始吗？', faqA1: '是的，创建店铺并添加产品完全免费，无需银行卡。',
    faqQ2: '创建店铺需要多久？', faqA2: '你可以在 5 分钟内创建店铺并添加第一个产品，无需任何技术。',
    faqQ3: 'AI 助手懂达里贾语吗？', faqA3: '懂，助手可用阿拉伯语、达里贾语、法语、英语和中文交流。',
    faqQ4: '我可以连接快递公司吗？', faqA4: '可以，平台支持连接快递公司并自动发货与追踪。',
    footExplore: '探索', lnkMarket: '市场', lnkPricing: '价格', lnkHow: '如何运作', lnkFaq: '常见问题', backTop: '回到顶部',
  },
};

// القدرات — التجارة أولاً، والذكاء الاصطناعي عنصر داعم (بترتيب Bento)
export const CAPS: Cap[] = [
  { Icon: ShoppingBag, k: 'products', c: '#FF6B35', feat: true },
  { Icon: Bot, k: 'ai', c: '#0EA5E9', wide: true },
  { Icon: Globe, k: 'market', c: '#7C3AED', wide: true },
  { Icon: Wrench, k: 'services', c: '#10B981' },
  { Icon: Store, k: 'store', c: '#F59E0B' },
  { Icon: Truck, k: 'delivery', c: '#3B82F6' },
  { Icon: MessageCircle, k: 'messages', c: '#16A34A' },
  { Icon: Calendar, k: 'bookings', c: '#8B5CF6' },
  { Icon: Gift, k: 'coupons', c: '#EC4899' },
  { Icon: BarChart3, k: 'analytics', c: '#F97316' },
  { Icon: ImageIcon, k: 'banner', c: '#A855F7' },
  { Icon: Languages, k: 'langs', c: '#06B6D4' },
];

// عناصر توضيحية (احتياط بصري فقط — مُعلَّمة بوضوح "مثال"، لا تُعرض كبيانات حقيقية)
export const SAMPLES: Listing[] = [
  { id: 's1', type: 'product', name: 'حذاء رياضي', price: 299, city: 'الدار البيضاء', sellerName: 'FootZone', ratingAvg: 4.8, emoji: '👟', sample: true },
  { id: 's2', type: 'product', name: 'فستان أنيق', price: 459, city: 'مراكش', sellerName: 'ModaChic', ratingAvg: 4.9, emoji: '👗', sample: true },
  { id: 's3', type: 'service', name: 'إصلاح كهربائي', price: 150, city: 'الرباط', sellerName: 'ProFix', ratingAvg: 5.0, emoji: '🛠️', sample: true },
  { id: 's4', type: 'product', name: 'ساعة ذكية', price: 849, city: 'طنجة', sellerName: 'TechVibe', ratingAvg: 4.7, emoji: '⌚', sample: true },
  { id: 's5', type: 'product', name: 'حقيبة جلدية', price: 599, city: 'فاس', sellerName: 'Artisan', ratingAvg: 4.9, emoji: '👜', sample: true },
  { id: 's6', type: 'service', name: 'تصميم شعار', price: 400, city: 'أكادير', sellerName: 'StudioX', ratingAvg: 5.0, emoji: '🎨', sample: true },
];

export const CITY_FALLBACK = ['الدار البيضاء', 'الرباط', 'مراكش', 'طنجة', 'أكادير', 'فاس'];
